[package]
name = "ddns"
version = "0.1.0"
edition = "2018"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5", features = ["rt", "macros"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
kube = { version = "0.52", features = ["derive"] }
kube-runtime = "0.52"
k8s-openapi = { version = "0.11", default-features = false, features = ["v1_20"] }
schemars = "0.8"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-opentelemetry = "0.12"
opentelemetry-jaeger = "0.12"
opentelemetry = "0.13"
anyhow = "1.0"
thiserror = "1.0"
futures-util = "0.3"
cloudflare = "0.8"

[dev-dependencies]
once_cell = "1.7"
