apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ddnss.api.sherlockholo.xyz

spec:
  group: api.sherlockholo.xyz
  names:
    kind: Ddns
    plural: ddnss
    shortNames:
      - dd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                  nullable: false

                domainName:
                  type: string
                  nullable: false

                domain:
                  type: string
                  nullable: false

              allOf:
                - properties:
                    serviceName: { }
                    domainName: { }
                    domain: { }

                  required:
                    - "serviceName"
                    - "domainName"
                    - "domain"

            status:
              type: object
              properties:
                status:
                  type: string

                serviceName:
                  type: string

                domainName:
                  type: string

                domain:
                  type: string

      subresources:
        status: { }

      additionalPrinterColumns:
        - jsonPath: .spec.serviceName
          name: ServiceName
          type: string

        - jsonPath: .spec.domainName
          name: DomainName
          type: string

        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date

        - jsonPath: .status.status
          name: Status
          type: string
