apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ddnss.api.sherlockholo.xyz

spec:
  group: api.sherlockholo.xyz
  names:
    kind: Ddns
    plural: ddnss
    shortNames:
      - dd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                  nullable: false

                domainName:
                  type: string
                  nullable: false

                domain:
                  type: string
                  nullable: false

              allOf:
                - properties:
                    serviceName: { }
                    domainName: { }
                    domain: { }

                  required:
                    - "serviceName"
                    - "domainName"
                    - "domain"

            status:
              type: object
              properties:
                status:
                  type: string

                serviceName:
                  type: string

                domainName:
                  type: string

                domain:
                  type: string

      subresources:
        status: { }

      additionalPrinterColumns:
        - jsonPath: .spec.serviceName
          name: ServiceName
          type: string

        - jsonPath: .spec.domainName
          name: DomainName
          type: string

        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date

        - jsonPath: .status.status
          name: Status
          type: string

---

apiVersion: v1
kind: Namespace
metadata:
  name: ddns-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ddns-controller
  namespace: ddns-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ddns-role

rules:
  - verbs:
      - get
      - watch
      - list

    apiGroups: [ "" ]

    resources:
      - services

  - verbs:
      - '*'

    apiGroups:
      - '*'

    resources:
      - ddnss

  - verbs:
      - '*'

    apiGroups:
      - '*'

    resources:
      - ddnss/status

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ddns-role-bind

subjects:
  - kind: ServiceAccount
    name: ddns-controller
    namespace: ddns-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ddns-role

---

apiVersion: v1
kind: Secret
metadata:
  name: ddns-secret
  namespace: ddns-system

data:
  token: YOUR-BASE64-TOKEN

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ddns-system
  name: ddns-controller
  labels:
    app: ddns-controller

spec:
  selector:
    matchLabels:
      app: ddns-controller

  template:
    metadata:
      labels:
        app: ddns-controller

    spec:
      containers:
        - name: ddns-controller
          image: sherlockholo/ddns:latest

          resources:
            limits:
              memory: 256Mi

          env:
            - name: CF_DNS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ddns-secret
                  key: token

            - name: RUST_LOG
              value: info

      serviceAccountName: ddns-controller
